Custom Name: "Custom Tnt" #Do Not Change The Name After Loading A World For The First Time (Probability Of World Corruption)
Explosion Radius: 10 #Big Explosions Can Impact Your Server Performance
Time Before Explode: 10
Works Underwater: true
Time Visible: true #False If You Don't Want To See The Time Above TNT
Time Format: "§g{time}"

Textures:
  Geometry: "" #Leave Blank If You Don't Use Custom Geometry
  Up: custom_tnt_top #The Top Texture Name Entered In The Pack (terrain_texture.json)
  Down: custom_tnt_bottom #The Bottom Texture Name Entered In The Pack (terrain_texture.json)
  North: custom_tnt_side #The North Texture Name Entered In The Pack (terrain_texture.json)
  South: custom_tnt_side #The South Texture Name Entered In The Pack (terrain_texture.json)
  East: custom_tnt_side #The East Texture Name Entered In The Pack (terrain_texture.json)
  West: custom_tnt_side #The West Texture Name Entered In The Pack (terrain_texture.json)
  